### ISSUE TITLE
logo on all wallpapers

### ISSUE THREAD

**Issue by dayne** [easybotics/t3-rpi-config-script#12]
script to impose logo onto each logo

**Comment by keptan** [comment]
all the files seem to be the same size, so can use the same method i use in https://github.com/keptan/superMioMusic to do this easily

**Comment by keptan** [comment]
https://github.com/easybotics/t3-rpi-config-script/commit/48101c82f918ce0bec2aa07334a65013517c9573
https://github.com/easybotics/t3-rpi-config-script/commit/d31c4418dc6025f6615894537481d308e2e2989a
