### ISSUE TITLE
Install xscreensaver

### ISSUE THREAD

**Issue by clowrey** [easybotics/t3-rpi-config-script#14]
Allows you to turn off the screen blanking/sleeping easily through the GUI

`sudo apt-get install xscreensaver`

Set screensaver mode to "Disable screen saver" - check how the GUI does it so it is changed properly. 

Check if CPU/power usage of the RPi is any different with screen enabled or disabled - maybe that is the only reason to leave the screen timeout enabled. 

This makes things like the selfie station with an image loading on the screen after a button pressed work well.

**Comment by keptan** [comment]
https://github.com/easybotics/t3-rpi-config-script/commit/532f296199a3a4c152e13964b25d7a2fbfe600c2
