### ISSUE TITLE
RPi config

### ISSUE THREAD

**Issue by dayne** [easybotics/t3-rpi-config-script#3]
- [x] Enable Camera 
- [x] Enable I2C enabled   `dtparm=i2c_arm=on`
- [x] Enable Serial Port   `enable_uart=1`
- [x] *Disable* Serial Console . 

This could likely be done via a standardized /boot/config.txt file.

**Comment by keptan** [comment]
https://github.com/raspberrypi-ui/rc_gui/blob/master/src/rc_gui.c#L23-L70

**Comment by keptan** [comment]
https://github.com/easybotics/t3-rpi-config-script/commit/a27a27e2a2072a693d37921e2ebceee594d7b8cf

if would be nice if we could disable the audio like this, and avoid editing the /boot/config file at all
