### ISSUE TITLE
additional cleanup items

### ISSUE THREAD

**Issue by dayne** [easybotics/t3-rpi-config-script#5]
- [x] customize the wallpaper
- [ ] set t3alliance website as default chrome website

hide the chrome extensions
- [x] ublock
- [x] h264ify

hide panel applet icons from application launch bar
- [x] wolfram alpha
- [x] mathmatica

**Comment by keptan** [comment]
https://github.com/easybotics/t3-rpi-config-script/commit/69d595577b9bab2f063a44741915df6565eabf47
